# Generated by Django 3.0.8 on 2022-05-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_customuser_courses'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('labelId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labelName', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='LabelValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelValue', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'LabelValues',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='body',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerPic',
            field=models.ImageField(default='', upload_to=questions.models.Answer.upload_location),
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoters',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoters',
            field=models.ManyToManyField(related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='questionId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='questionPic',
            field=models.ImageField(default='', upload_to=questions.models.Question.upload_location),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='questions.Question'),
        ),
        migrations.CreateModel(
            name='QuestionLabel',
            fields=[
                ('questionLabelId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labelValue', models.CharField(max_length=50)),
                ('labelName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Label', to_field='labelName')),
                ('labeledByUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Question')),
            ],
            options={
                'db_table': 'QuestionLabels',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='possibleValues',
            field=models.ManyToManyField(to='questions.LabelValue'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2022)),
                ('semester', models.CharField(choices=[('A', 'A'), ('B', 'B')], default=('A', 'A'), max_length=1)),
                ('examType', models.CharField(choices=[('A', 'A'), ('B', 'B')], default=('A', 'A'), max_length=1)),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Course', to_field='courseName')),
                ('teacher', models.ForeignKey(limit_choices_to={'isTeacher': True}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'Exams',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='examId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Exam'),
            preserve_default=False,
        ),
    ]
