# Generated by Django 3.0.8 on 2022-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20220504_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
