# Generated by Django 3.0.8 on 2022-05-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20220506_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
