# Generated by Django 3.0.8 on 2022-05-07 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20220507_1630'),
        ('questions', '0010_auto_20220506_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='courseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course', to_field='courseName'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default='cdf09df6-6e9e-42b0-928b-b119ce4f86bb', limit_choices_to={'isTeacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='examId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Exam'),
        ),
        migrations.AlterField(
            model_name='questionlabel',
            name='labelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Label', to_field='labelName'),
        ),
        migrations.AlterField(
            model_name='questionlabel',
            name='labeledByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='questionlabel',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
