# Generated by Django 3.0.8 on 2022-05-07 19:14

import django.core.validators
from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20220507_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answerPic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionPic',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerPDF',
            field=models.FileField(blank=True, default='', upload_to=questions.models.Answer.upload_location, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='question',
            name='questionPDF',
            field=models.FileField(default='', upload_to=questions.models.Question.upload_location, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
