# Generated by Django 3.0.8 on 2022-05-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20220507_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='examId',
            new_name='examUniqueName',
        ),
    ]
