# Generated by Django 3.0.8 on 2022-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20220507_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
