# Generated by Django 3.0.8 on 2022-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_questiontopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ranking',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
