# Generated by Django 3.0.8 on 2022-05-04 12:48

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Schools',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userPic',
            field=models.ImageField(default='users/uploads/userPics/default_userPic.png', upload_to=users.models.CustomUser.upload_location),
        ),
    ]
