# Generated by Django 3.0.8 on 2022-05-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220504_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='facultyName',
            field=models.ForeignKey(default='a8098c1a-f86e-11da-bd1a-00112444be1e', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Faculty', to_field='facultyName'),
        ),
    ]
