# Generated by Django 3.0.8 on 2022-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220504_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='participants', to='users.Course'),
        ),
    ]
