# Generated by Django 3.0.8 on 2022-05-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schoolName',
            field=models.ForeignKey(default='Computer Science', on_delete=django.db.models.deletion.CASCADE, to='users.School', to_field='schoolName'),
        ),
        migrations.AlterField(
            model_name='school',
            name='facultyName',
            field=models.ForeignKey(default='Exact Science', on_delete=django.db.models.deletion.CASCADE, to='users.Faculty', to_field='facultyName'),
        ),
    ]
