# Generated by Django 3.0.8 on 2022-05-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220507_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='facultyName',
            field=models.ForeignKey(default='Engineering', on_delete=django.db.models.deletion.CASCADE, to='users.Faculty', to_field='facultyName'),
        ),
    ]
