# Generated by Django 3.0.8 on 2022-05-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220507_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schoolName',
            field=models.ForeignKey(default='Electrical Engineering', on_delete=django.db.models.deletion.CASCADE, to='users.School', to_field='schoolName'),
        ),
    ]
