# Generated by Django 3.0.8 on 2022-05-07 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220507_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, to='users.Topic'),
        ),
    ]
