# Generated by Django 3.0.8 on 2022-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220507_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rankScore',
            field=models.IntegerField(default=0),
        ),
    ]
